import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { parseDocs } from '../lib/common.mjs';
const root = fileURLToPath(new URL('../', import.meta.url));
const read = path => readFileSync(join(root, path));
test('Kubara app listener, service and readiness port agree with the retained container response', () => {
  const receipt = JSON.parse(read('proofs/shop-http-2026-09-09/receipt.json'));
  const snapshot = read('proofs/shop-http-2026-09-09/app.yaml');
  assert.equal(createHash('sha256').update(snapshot).digest('hex'), receipt.appSha256);
  const objects = parseDocs(read('apps/shop-web-kubara.yaml').toString());
  const pod = objects.find(o => o.kind === 'Deployment').spec.template;
  const container = pod.spec.containers[0];
  const service = objects.find(o => o.kind === 'Service');
  assert.equal(receipt.scope, 'single-local-container-not-kubernetes');
  assert.equal(container.image, receipt.image);
  assert.deepEqual(container.args, receipt.runs[1].args);
  assert.deepEqual(receipt.defaultCmd, ['pause']);
  assert.equal(receipt.runs[0].httpStatus, null);
  assert.equal(receipt.runs[1].httpStatus, 200);
  assert.ok(receipt.runs[1].response.trim());
  assert.ok(receipt.runs.every(r => r.cleanup));
  assert.equal(service.spec.ports[0].targetPort, container.ports[0].containerPort);
  assert.equal(container.readinessProbe.httpGet.port, service.spec.ports[0].targetPort);
  assert.equal(container.readinessProbe.httpGet.path, '/');
  assert.equal(container.args.find(a => a.startsWith('--port=')), `--port=${service.spec.ports[0].targetPort}`);
  for (const [key,value] of Object.entries(service.spec.selector)) assert.equal(pod.metadata.labels[key], value);
});
