apiVersion: helm-expt.confighub.com/v1alpha1
kind: Stack
metadata:
  name: data-services
spec:
  description: "A stateful data tier: cache, relational database, and message queue."
  components:
    - name: redis
      bundle: "oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bundles/workshop-redis@sha256:0db01a1068b7a18ec99a0f5c287dcc0b3765b81c60af44da798c52540c810fe9"
      receipt: "receipts/workshop/redis.json"
    - name: postgresql
      bundle: "oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bundles/workshop-postgresql@sha256:6eaabcd4a6d0c3445d21759eb99b498a0aa7c8ba55228575adeeecd8cfd1ed6f"
      receipt: "receipts/workshop/postgresql.json"
    - name: rabbitmq
      bundle: "oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bundles/workshop-rabbitmq@sha256:d94f26b2a0cbf1b02966855ff1f7c61742c7b54d599f2fa99539ccc97ac94e01"
      receipt: "receipts/workshop/rabbitmq.json"