apiVersion: helm-expt.confighub.com/v1alpha1
kind: Stack
metadata:
  name: observability-base
spec:
  description: "A base observability platform: certificates, cluster metrics, and the Prometheus stack."
  components:
    - name: cert-manager
      bundle: "oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bundles/workshop-cert-manager@sha256:4bd8b82b898da503a774d47348532d85a18910ca635ae2f772354777636ca134"
      receipt: "receipts/workshop/cert-manager.json"
    - name: metrics-server
      bundle: "oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bundles/workshop-metrics-server@sha256:31bb7fedb9866cfad873848733eb5fc06071ff41222ac07bf9f1475f220ce868"
      receipt: "receipts/workshop/metrics-server.json"
    - name: kube-prometheus-stack
      bundle: "oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bundles/workshop-kube-prometheus-stack@sha256:1c485c529c60588924e11a6e3f27ff8899802045672c1f80aa26a049e49d6a6a"
      receipt: "receipts/workshop/kube-prometheus-stack.json"