apiVersion: helm-expt.confighub.com/v1alpha1
kind: Stack
metadata:
  name: observability-base
spec:
  description: "A base observability platform: certificates, cluster metrics, and the Prometheus stack."
  components:
    - name: cert-manager
      bundle: "oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bundles/workshop-cert-manager@sha256:76314143ef5017951d1351732eb0796707e73797c2a67ace5fb4202a62bbad70"
      receipt: "receipts/workshop/cert-manager.json"
    - name: metrics-server
      bundle: "oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bundles/workshop-metrics-server@sha256:db0795803b4a7d2ac7112ef6b5939174266022d75764e757cdd11db72d265fff"
      receipt: "receipts/workshop/metrics-server.json"
    - name: kube-prometheus-stack
      bundle: "oci://europe-west1-docker.pkg.dev/nth-fort-499605-q5/helm-expt/bundles/workshop-kube-prometheus-stack@sha256:d46ddb13b9453b54f0125035a435349b0053dde7dd945ac63249f1834eafbac2"
      receipt: "receipts/workshop/kube-prometheus-stack.json"